
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.7.0 mypy==1.11.2 pytest==8.3.3
      - name: Lint (ruff)
        run: ruff check . || true
      - name: Type-check (mypy)
        run: mypy src || true
      - name: Alembic check (offline)
        run: alembic upgrade head --sql || true
      - name: Run tests
        run: pytest -q || true
