"""Restructuración eventos CRUD

Revision ID: b6a00be08052
Revises: 053c59eb25b1
Create Date: 2025-11-09 03:06:28.254506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b6a00be08052'
down_revision: Union[str, None] = '053c59eb25b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Enum('SANITARIO', 'HISTORICO', 'PRODUCCION', name='tipo_evento_grupo_enum'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('multi_animal', sa.Boolean(), nullable=False),
    sa.Column('estado_resultante', sa.Enum('SANO', 'EN_OBSERVACION', 'ENFERMO', name='tipo_evento_estado_resultante_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo', 'nombre', name='uq_tipo_evento_grupo_nombre')
    )
    op.create_index(op.f('ix_tipo_evento_grupo'), 'tipo_evento', ['grupo'], unique=False)
    op.create_index(op.f('ix_tipo_evento_id'), 'tipo_evento', ['id'], unique=False)
    op.create_table('animal_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('usuario_dni', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_dni'], ['datos_del_usuario.numero_de_dni'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_dni', 'nombre', name='uq_animal_group_usuario_nombre')
    )
    op.create_index(op.f('ix_animal_groups_id'), 'animal_groups', ['id'], unique=False)
    op.create_table('catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('usuario_dni', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_dni'], ['datos_del_usuario.numero_de_dni'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo', 'nombre', 'usuario_dni', name='uq_catalogo_grupo_nombre_usuario')
    )
    op.create_index(op.f('ix_catalogo_grupo'), 'catalogo', ['grupo'], unique=False)
    op.create_index(op.f('ix_catalogo_id'), 'catalogo', ['id'], unique=False)
    op.create_table('eventos_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo_evento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('descendencia_cuis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipo_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_historicos_id'), 'eventos_historicos', ['id'], unique=False)
    op.create_table('animal_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('animal_cui', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['animal_cui'], ['animales.cui'], ),
    sa.ForeignKeyConstraint(['group_id'], ['animal_groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'animal_cui')
    )
    op.create_table('evento_historico_animales',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('animal_cui', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['animal_cui'], ['animales.cui'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_historicos.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'animal_cui')
    )
    op.create_table('evento_sanitario_animales',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('animal_cui', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['animal_cui'], ['animales.cui'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_sanitarios.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'animal_cui')
    )
    op.add_column('animales', sa.Column('madre_cui', sa.String(length=11), nullable=True))
    op.add_column('animales', sa.Column('padre_cui', sa.String(length=11), nullable=True))
    op.create_foreign_key(None, 'animales', 'animales', ['padre_cui'], ['cui'])
    op.create_foreign_key(None, 'animales', 'animales', ['madre_cui'], ['cui'])
    op.add_column('eventos_produccion', sa.Column('tipo_evento_id', sa.Integer(), nullable=False))
    op.add_column('eventos_produccion', sa.Column('unidad', sa.String(), nullable=False))
    op.alter_column('eventos_produccion', 'valor',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               nullable=False,
               postgresql_using='valor::double precision')
    op.create_foreign_key(None, 'eventos_produccion', 'tipo_evento', ['tipo_evento_id'], ['id'])
    op.drop_column('eventos_produccion', 'tipo_evento')
    op.add_column('eventos_sanitarios', sa.Column('tipo_evento_id', sa.Integer(), nullable=False))
    op.add_column('eventos_sanitarios', sa.Column('tratamiento_id', sa.Integer(), nullable=True))
    op.drop_constraint('eventos_sanitarios_animal_cui_fkey', 'eventos_sanitarios', type_='foreignkey')
    op.create_foreign_key(None, 'eventos_sanitarios', 'tipo_evento', ['tipo_evento_id'], ['id'])
    op.create_foreign_key(None, 'eventos_sanitarios', 'catalogo', ['tratamiento_id'], ['id'])
    op.drop_column('eventos_sanitarios', 'tipo_evento')
    op.drop_column('eventos_sanitarios', 'animal_cui')
    op.add_column('inventario_items', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventario_items', 'catalogo', ['categoria_id'], ['id'])
    op.drop_column('inventario_items', 'categoria')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_items', sa.Column('categoria', postgresql.ENUM('ALIMENTO', 'MEDICAMENTO', 'VACUNA', 'EQUIPO', name='inventario_categoria_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventario_items', type_='foreignkey')
    op.drop_column('inventario_items', 'categoria_id')
    op.add_column('eventos_sanitarios', sa.Column('animal_cui', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.add_column('eventos_sanitarios', sa.Column('tipo_evento', postgresql.ENUM('VACUNACION', 'TRATAMIENTO', 'DESPARASITACION', name='evento_sanitario_tipo_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'eventos_sanitarios', type_='foreignkey')
    op.drop_constraint(None, 'eventos_sanitarios', type_='foreignkey')
    op.create_foreign_key('eventos_sanitarios_animal_cui_fkey', 'eventos_sanitarios', 'animales', ['animal_cui'], ['cui'])
    op.drop_column('eventos_sanitarios', 'tratamiento_id')
    op.drop_column('eventos_sanitarios', 'tipo_evento_id')
    op.add_column('eventos_produccion', sa.Column('tipo_evento', postgresql.ENUM('PESAJE', 'PARTO', 'CONTROL_LECHERO', name='evento_produccion_tipo_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'eventos_produccion', type_='foreignkey')
    op.alter_column('eventos_produccion', 'valor',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('eventos_produccion', 'unidad')
    op.drop_column('eventos_produccion', 'tipo_evento_id')
    op.drop_constraint(None, 'animales', type_='foreignkey')
    op.drop_constraint(None, 'animales', type_='foreignkey')
    op.drop_column('animales', 'padre_cui')
    op.drop_column('animales', 'madre_cui')
    op.drop_table('evento_sanitario_animales')
    op.drop_table('evento_historico_animales')
    op.drop_table('animal_group_members')
    op.drop_index(op.f('ix_eventos_historicos_id'), table_name='eventos_historicos')
    op.drop_table('eventos_historicos')
    op.drop_index(op.f('ix_catalogo_id'), table_name='catalogo')
    op.drop_index(op.f('ix_catalogo_grupo'), table_name='catalogo')
    op.drop_table('catalogo')
    op.drop_index(op.f('ix_animal_groups_id'), table_name='animal_groups')
    op.drop_table('animal_groups')
    op.drop_index(op.f('ix_tipo_evento_id'), table_name='tipo_evento')
    op.drop_index(op.f('ix_tipo_evento_grupo'), table_name='tipo_evento')
    op.drop_table('tipo_evento')
    # ### end Alembic commands ###
